# Generated by Django 3.1.2 on 2020-11-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meet_name', models.CharField(max_length=200, null=True)),
                ('vote_list', models.CharField(max_length=255, null=True)),
                ('meeting_date', models.CharField(max_length=50, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '开会记录',
                'db_table': 'meeting',
                'ordering': ['pk'],
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='uservote',
            options={'managed': False, 'ordering': ['-update_time'], 'verbose_name': '用户投票记录'},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'managed': False, 'ordering': ['pk'], 'verbose_name': '投票记录'},
        ),
    ]
